rust-exampes:
  image: "rust:latest"
  stage: test
  parallel:
    matrix:
      - BOARD: PocketBeagle-2
        EXAMPLE:
        - blinky
        - button
        - fade
        - eeprom
        - light_sensor
        - seven_segment
        - tonal_buzzer
        - rgb_led
  before_script:
    - rustup component add clippy
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cd ${BOARD}/${EXAMPLE}/rust
    - cargo clippy --no-deps
    - cargo build
    - cargo test

python-library:
  image: "python:alpine"
  stage: test
  before_script:
    - pip install build
  script:
    - cd Libraries/python/beagle_linux_sdk
    - python -m build
