rust-exampes:
  image: "rust:latest"
  stage: test
  parallel:
    matrix:
      - BOARD: PocketBeagle2
        EXAMPLE:
        - blinky
  before_script:
    - rustup component add clippy
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cd ${BOARD}/${EXAMPLE}/rust
    - cargo clippy --no-deps
    - cargo build
    - cargo test
