[package]
name = "button"
description = "Simple example to detect button presses"
version = "0.1.0"
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
gpio-cdev = "0.6.0"
