name: Run Checks

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  rust:
    strategy:
      matrix:
        board: [ PocketBeagle-2 ]
        example: [ blinky, button, fade, eeprom, light_sensor, seven_segment, tonal_buzzer, rgb_led ]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select rust toolchain
        run: rustup toolchain install stable --profile minimal
      - name: Use caching
        uses: Swatinem/rust-cache@v2
      - name: Run checks
        working-directory: ${{ matrix.board }}/${{ matrix.example }}/rust
        run: cargo clippy --all-targets --all-features --no-deps
      - name: Build
        working-directory: ${{ matrix.board }}/${{ matrix.example }}/rust
        run: cargo build
      - name: Run tests
        working-directory: ${{ matrix.board }}/${{ matrix.example }}/rust
        run: cargo test
